"""empty message

Revision ID: 922f85601faf
Revises: 
Create Date: 2020-06-21 13:32:01.121909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922f85601faf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_airline', sa.String(length=50), nullable=False),
    sa.Column('airline', sa.String(length=50), nullable=True),
    sa.Column('aircraft_type', sa.String(length=50), nullable=True),
    sa.Column('current', sa.Integer(), nullable=True),
    sa.Column('future', sa.Integer(), nullable=True),
    sa.Column('historic', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('average_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fleet')
    # ### end Alembic commands ###
